CREATE TABLE discs_raw AS
		SELECT *
		FROM discgolf.axiom
	UNION ALL
		SELECT *
		FROM discgolf.birdie
	UNION ALL
		SELECT *
		FROM discgolf.dga
	UNION ALL
		SELECT *
		FROM discgolf.clash
	UNION ALL
		SELECT *
		FROM discgolf.dino
	UNION ALL
		SELECT *
		FROM discgolf.discmania
	UNION ALL
		SELECT *
		FROM discgolf.dynamicdiscs
	UNION ALL
		SELECT *
		FROM discgolf.discraft
	UNION ALL
		SELECT *
		FROM discgolf.finishline
	UNION ALL
		SELECT *
		FROM discgolf.hooligan
	UNION ALL
		SELECT *
		FROM discgolf.gateway
	UNION ALL
		SELECT *
		FROM discgolf.innova
	UNION ALL
		SELECT *
		FROM discgolf.infinitediscs
	UNION ALL
		SELECT *
		FROM discgolf.jester
	UNION ALL
		SELECT *
		FROM discgolf.latitude64
	UNION ALL
		SELECT *
		FROM discgolf.kastaplast
	UNION ALL
		SELECT *
		FROM discgolf.millennium
	UNION ALL
		SELECT *
		FROM discgolf.lonestar
	UNION ALL
		SELECT *
		FROM discgolf.mvp
	UNION ALL
		SELECT *
		FROM discgolf.mint
	UNION ALL
		SELECT *
		FROM discgolf.prodigy
	UNION ALL
		SELECT *
		FROM discgolf.streamline
	UNION ALL
		SELECT *
		FROM discgolf.thoughtspace
	UNION ALL
		SELECT *
		FROM discgolf.trashpanda
	UNION ALL
		SELECT *
		FROM discgolf.viking
	UNION ALL
		SELECT *
		FROM discgolf.westside
	UNION ALL
		SELECT *
		FROM discgolf.yikun
;